/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.poligonos.vista;

import co.appreactor.poligonos.persistencia.Cuadrilatero;
import co.appreactor.poligonos.persistencia.Figura;
import co.appreactor.poligonos.persistencia.Punto2d;
import co.appreactor.poligonos.persistencia.Triangulo;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lord_Nightmare
 */
public class Ventana extends javax.swing.JFrame {

    private PanelLienzo canvas;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        // estructura para darle valores al combobox
        DefaultComboBoxModel dcb = new DefaultComboBoxModel();
        txtColorFondo.setBackground(Color.white);
        // agregar los elementos que se pueden seleccionar
        dcb.addElement("Seleccione una figura..."); // 0
        dcb.addElement("Triangulo"); // 1
        dcb.addElement("Cuadrilatero"); // 2
        // agregar el modelo al combobox
        cboTipoFigura.setModel(dcb);
        //canvas = new PanelLienzo();
        //canvas.setVisible(true);
        //plCanvas = new PanelLienzo();
        canvas = new PanelLienzo();
        canvas.setBounds(4, 4, 450, 450);
        this.add(canvas);
        canvas.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHud = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtXuno = new javax.swing.JTextField();
        txtYuno = new javax.swing.JTextField();
        txtXdos = new javax.swing.JTextField();
        txtYdos = new javax.swing.JTextField();
        txtXtres = new javax.swing.JTextField();
        txtYtres = new javax.swing.JTextField();
        txtXcuatro = new javax.swing.JTextField();
        txtYcuatro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cboTipoFigura = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtColorFondo = new javax.swing.JTextField();
        btnElegirColor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiguras = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eje");

        jLabel2.setText("X");

        jLabel3.setText("Y");

        jLabel4.setText("Vertice 1");

        jLabel5.setText("Vertice 2");

        jLabel6.setText("Vertice 3");

        jLabel7.setText("Vertice 4");

        txtXuno.setText("100");

        txtYuno.setText("100");

        txtXdos.setText("300");

        txtYdos.setText("100");

        txtXtres.setText("200");

        txtYtres.setText("250");

        cboTipoFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Color");

        txtColorFondo.setEditable(false);

        btnElegirColor.setText("Elegir");
        btnElegirColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plHudLayout = new javax.swing.GroupLayout(plHud);
        plHud.setLayout(plHudLayout);
        plHudLayout.setHorizontalGroup(
            plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(cboTipoFigura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(plHudLayout.createSequentialGroup()
                        .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plHudLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXcuatro))
                            .addGroup(plHudLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plHudLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(plHudLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXtres)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtYdos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtYtres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtYcuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plHudLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColorFondo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElegirColor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plHudLayout.createSequentialGroup()
                        .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plHudLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXuno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtXdos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYuno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        plHudLayout.setVerticalGroup(
            plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtXuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtXdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtXtres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYtres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtXcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTipoFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegirColor))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblFiguras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Forma", "Color", "Coordenadas", "Lados", "Area", "Perimetro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFiguras.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblFiguras);
        if (tblFiguras.getColumnModel().getColumnCount() > 0) {
            tblFiguras.getColumnModel().getColumn(1).setResizable(false);
        }

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plHud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plHud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar)
                .addGap(152, 152, 152)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (txtColorFondo.getBackground().equals(Color.white)) {
            JOptionPane.showMessageDialog(rootPane, "Debe elegir un color diferente al fondo del lienzo", "Elección de color", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Figura fig;
        switch (cboTipoFigura.getSelectedIndex()) {
            case 1:
                fig = generarTriangulo();
                break;
            case 2:
                fig = generarCuadrilatero();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Tipo de figura no valida", "Elección de figura", JOptionPane.WARNING_MESSAGE);
                return;
        }
        if (fig != null) {
            insertarFiguraTabla(fig);
        }
        canvas.repaint();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnElegirColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirColorActionPerformed
        txtColorFondo.setBackground(JColorChooser.showDialog(rootPane, "Elegir color para figura", Color.RED));
    }//GEN-LAST:event_btnElegirColorActionPerformed

    private Figura generarTriangulo() {
        Triangulo tri = new Triangulo(txtColorFondo.getBackground(), "Un triangulo mas");
        tri.getVertices()[0] = new Punto2d(
                Integer.parseInt(txtXuno.getText()), Integer.parseInt(txtYuno.getText())
        );
        tri.getVertices()[1] = new Punto2d(
                Integer.parseInt(txtXdos.getText()), Integer.parseInt(txtYdos.getText())
        );
        tri.getVertices()[2] = new Punto2d(
                Integer.parseInt(txtXtres.getText()), Integer.parseInt(txtYtres.getText())
        );
        tri.calcularLados();
        canvas.getListaFiguras().add(tri);
        return tri;
    }

    private Figura generarCuadrilatero() {
        Cuadrilatero cua = new Cuadrilatero(txtColorFondo.getBackground(), "Un cuadrado mas");
        cua.getVertices()[0] = new Punto2d(
                Integer.parseInt(txtXuno.getText()), Integer.parseInt(txtYuno.getText())
        );
        cua.getVertices()[1] = new Punto2d(
                Integer.parseInt(txtXdos.getText()), Integer.parseInt(txtYdos.getText())
        );
        cua.getVertices()[2] = new Punto2d(
                Integer.parseInt(txtXtres.getText()), Integer.parseInt(txtYtres.getText())
        );
        cua.getVertices()[3] = new Punto2d(
                Integer.parseInt(txtXcuatro.getText()), Integer.parseInt(txtYcuatro.getText())
        );
        cua.calcularLados();
        canvas.getListaFiguras().add(cua);
        return cua;
    }

    private void insertarFiguraTabla(Figura fig) {
        ((DefaultTableModel) tblFiguras.getModel()).addRow(
                new Object[]{
                    (fig instanceof Triangulo) ? "Triangulo" : "Cuadrilatero",
                    "#" + Integer.toHexString(fig.getColor().getRGB()).substring(2),
                    implotarCoordenadas(fig),
                    implotarLados(fig),
                    Math.round(fig.area() * 100.0) / 100.0,
                    Math.round(fig.perimetro() * 100.0) / 100.0
                }
        );
    }

    private String implotarCoordenadas(Figura fig) {
        StringBuilder sb = new StringBuilder();
        for (Punto2d vertice : fig.getVertices()) {
            sb.append(extraerCoordenadaString(vertice));
            sb.append(",");
        }
        return sb.toString().substring(0, sb.toString().length() - 1);
    }

    private String extraerCoordenadaString(Punto2d vertice) {
        return "(" + vertice.getX() + "," + vertice.getY() + ")";
    }

    private String implotarLados(Figura fig) {
        StringBuilder sb = new StringBuilder();
        for (double lado : fig.getLados()) {
            sb.append(Math.round(lado * 100.0) / 100.0);
            sb.append(",");
        }
        return "(" + sb.toString().substring(0, sb.toString().length() - 1) + ")";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegirColor;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cboTipoFigura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel plHud;
    private javax.swing.JTable tblFiguras;
    private javax.swing.JTextField txtColorFondo;
    private javax.swing.JTextField txtXcuatro;
    private javax.swing.JTextField txtXdos;
    private javax.swing.JTextField txtXtres;
    private javax.swing.JTextField txtXuno;
    private javax.swing.JTextField txtYcuatro;
    private javax.swing.JTextField txtYdos;
    private javax.swing.JTextField txtYtres;
    private javax.swing.JTextField txtYuno;
    // End of variables declaration//GEN-END:variables
}
